version: 1
services:
  - type: web
    name: my-laravel-app
    env: php
    runtime: php # Forzar la detección de PHP
    buildCommand: "composer install --no-dev -o"
    startCommand: "php -S 0.0.0.0:8000 -t public"
